name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # Job 1 : Tests et formatage
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18.18.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier - Format Check
        run: npm run check-format

      - name: Run unit tests
        run: npm run test

  # Job 2 : SonarQube - Analyse de la qualité du code
  sonarqube:
    name: SonarQube Analysis
    runs-on: windows-latest
    needs: tests # Cette étape dépend du job de tests (doit réussir avant de lancer SonarQube)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Job 3 : Déploiement sur un environnement de test
  deploy:
    runs-on: ubuntu-latest
    needs: sonarqube # Cette étape dépend du job SonarQube
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18.18.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt 3 project
        run: npm run build

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
