name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # Job 1 : Tests
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18.18.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint - Liting
        run: npm run lint

      - name: Run unit tests
        run: npm run test

  # Job 2 : Déploiement sur un environnement de test
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18.18.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt 3 project
        run: npm run build

      - name: Deploy to Vercel
        run: npm run deploy -- --token ${{ secrets.VERCEL_TOKEN }}
