name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: 🧪 Lint, Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: npm ci

      - name: Lint - ESLint
        run: npm run lint

      - name: Unit & Integration tests - Vitest
        run: npm run test

  #  coveralls:
  #    name: 📊 Coveralls - Not in use
  #    runs-on: ubuntu-latest
  #    needs: tests
  #    steps:
  ##      - name: Checkout code
  ##        uses: actions/checkout@v3
  ##
  ##      - name: Install dependencies
  ##        run: npm ci
  ##
  ##      - name: Run Coveralls
  ##        run: npm run coveralls
  ##        env:
  ##          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  e2e-tests:
    name: 🔍 E2E Tests (Playwright)
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build project
        run: npm run build

      - name: Start Nuxt server
        run: npm run preview &
        env:
          NODE_ENV: test

      - name: Ensure @actions/core is installed
        run: npm install @actions/core

      - name: Run Playwright tests on preview deployment
        env:
          PLAYWRIGHT_BASE_URL: ${{ steps.vercel.outputs.url }}
        run: |
          npx playwright test tests/e2e

  sonarqube:
    name: 🔎 SonarQube Analysis
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
