name: Close Issue when PR is merged

on:
  pull_request:
    types:
      - closed

jobs:
  close_issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Close related issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.pull_request.title }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
